sudo: required
language: generic #rakefile not found fix
services:
  - docker

before_install: # we do not use production dockerfile because will not allow testing
                #only doing react unit tests but could easily expand to worker and server
  - docker build -t stephenc0821/react-test -f ./client/Dockerfile.dev ./client #ending mean looks into client dir for build ctx

script: #commands to run test suite
  - docker run -e CI=true stephenc0821/react-test npm run test #need zero exit code for travis so run w/ CI env flag


after_success: #use prod dockerfiles now so no need to specify dockerfile name
  - docker build -t stephenc0821/multi-client ./client
  - docker build -t stephenc0821/multi-server ./server
  - docker build -t stephenc0821/multi-worker ./worker
  - docker build -t stephenc0821/multi-nginx ./nginx

  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push built images to docker hub
  - docker push stephenc0821/multi-client
  - docker push stephenc0821/multi-nginx
  - docker push stephenc0821/multi-servergit
  - docker push stephenc0821/multi-worker

  


# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "frontend"
#   env: "Frontend-env-1"
#   bucket_name: "elasticbeanstalk-us-east-1-381492306175"
#   bucket_path: "frontend"
#   on:
#     branch: master
#   access_key_id: "$AWS_FRONTEND_KEY"
#   secret_access_key: "$AWS_FRONTEND_SECRET" #added aws cli keys/secret to travis settings