version: '3'

services:
  nginx: 
    restart: always #we need this to run always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  worker: #you kinda want this to stay off if crashes cuz fibonacci is expensive and do not wanna consume cpu cycles
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/node/app/node_modules 
      - ./worker:/home/node/app #anytime docker looks to this directory it will reroute to our server dir here
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules #bookmark hold makes sure dir inside container will not get overwritten by node_modules in our host client dir
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0 #webpack likes ws with dev server to detect changes
  api: #had to call service api to avoid keyword in nginx default.conf
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /home/node/app/node_modules #tells docker do not make changes to this directory
      - ./server:/home/node/app #anytime docker looks to this directory it will reroute to our server dir here
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  