version: '3'
services:
  nginx: 
    image: stephenc0821/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  worker: 
    image: stephenc0821/mutli-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: stephenc0821/multi-client #travis CI sends image to dockerhub
    mem_limit: 128m
    hostname: client
  server: #had to call service api to avoid keyword in nginx default.conf
    image: stephenc0821/muli-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  